### ISSUE TITLE
About Trainning new PR2 v5.0.0 515Y-926R Qiime2 Classifier

### ISSUE THREAD

**Issue by shanexuuu** [jcmcnch/eASV-pipeline-for-515Y-926R#5]
Hi,

Thanks for your pipeline! I would like to train PR2 version 5.0.0 515Y-926R Qiime2 Classifier. I was wondering how did you train the pr2_version_4.14.0_SSU-515FY-926R-classifier.qza. I used the following setting to train my classifier:

qiime feature-classifier extract-reads \
  --i-sequences pr2_version_5.0.0_SSU_mothur.qza \
  --p-f-primer GTGYCAGCMGCCGCGGTAA \
  --p-r-primer CCGYCAATTYMTTTRAGTTT \
  --p-trunc-len 120 \
  --p-min-length 100 \
  --p-max-length 400 \
  --o-reads pr2_version_5.0.0_SSU_515Y_926Rseqs.qza

qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads pr2_version_5.0.0_SSU_515Y_926Rseqs.qza \
  --i-reference-taxonomy pr2_version_5.0.0_SSU_mothur_tax.qza \
  --o-classifier pr2_version_5.0.0_SSU-515FY-926R-classifier.qza

I am not sure whether the  " --p-trunc-len 120  --p-min-length 100  --p-max-length 400 " correct?

Many thanks!

**Comment by jcmcnch** [comment]
Hi,

Thanks for your interest in the pipeline! I put together a repo describing this since I always forget myself. You can find it and the associated scripts here:

https://github.com/jcmcnch/515F-Y_926R_database_construction/tree/main

I haven't tried this in a while, so some of the syntax might possibly have changed in the latest qiime2 versions but hopefully not. Hopefully that is enough to answer your question, but if not, please let me know in another comment.

Best,
Jesse

**Comment by shanexuuu** [comment]
Hi Jesse,

Thanks a lot for this! I followed your scripts (except "qiime rescript dereplicate --p-rank-handles 'disable' ", since --p-rank-handles 'silva' always failed) and successfully trainned a new PR2 v5.0.0 515Y-926R Classifier.

Cheers,
Shane
